package euler;

/**
 * Even Fibonacci Numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1,2,3,5,8,13,21,34,55,89,...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class EulerZwei {
    public static void main(String[] args) {
        int nummer1 = 0;
        int nummer2 = 1;
        int nummer3 = 0;
        int sum = 0;
        while (nummer3 < 4_000_000){
            nummer3 = nummer1+nummer2;
            if(nummer3 % 2 == 0){
                sum += nummer3;
            }
            nummer1 = nummer2;
            nummer2 = nummer3;
        }
        System.out.print("Sum of even values in Fibonocci: " + sum);
    }
}
